---
# Playbook que sobe tudo

- name: Play que sobe a aplicação
  hosts: clienterhel7.s2linux.local
  become: true
  gather_facts: false
  tasks:
    - name: Sobe o daemon do apache
      ansible.builtin.systemd_service:
        name: "httpd.service"
        state: "started"

- name: Play que sobe o banco
  hosts: clienterhel8.s2linux.local   
  become: true
  gather_facts: false
  tasks:
    - name: Para o daemon do postgresql
      ansible.builtin.systemd_service: 
        name: "postgresql.service"
        state: "started"
...
