---
# Playbook que valida a aplicação

- name: Play que valida a aplicação
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Verifica o status dos processos da máquina
      ansible.builtin.service_facts:
      delegate_to: clienterhel7.s2linux.local

    - name: Verifica a resposta da URL de teste
      ansible.builtin.uri:
        url: http://clienterhel7.s2linux.local/pub
        method: GET
        status_code: 200
        return_content: true
      register: retorno

    - name: Gera um erro caso o daemon do apache não esteja no ar
      vars:
        ttt: "Aplicação do Roger"
      ansible.builtin.assert:
        that:
          - ansible_facts.services["httpd.service"].state == "running"
          - ttt in retorno.content

