---
- name: Play que realiza a atualização de SO das máquinas de aplicação e banco
  hosts: clienterhel[7-9].s2linux.local
  become: true
  gather_facts: false
  tasks:
    - name: Atualiza o SO
      ansible.builtin.dnf:
        name: "*"
        state: latest
      notify: "Reboot Action"

  handlers:
    - name: Reinicia a máquina, caso haja atualizações de pacotes
      ansible.builtin.reboot:
        reboot_timeout: 2700
      listen: "Reboot Action"
...
